from typing import Protocol

from app.domain.peca.entities import Peca


class PecaRepositoryProtocol(Protocol):
    async def criar(self, peca: Peca) -> Peca: ...
    async def buscar_por_id(self, peca_id: int) -> Peca | None: ...
    async def listar(self) -> list[Peca]: ...
    async def atualizar(self, peca: Peca) -> Peca: ...
    async def remover(self, peca_id: int) -> None: ...

    async def decrementar_estoque(self, peca_id: int, quantidade: int) -> Peca:
        """UPDATE atômico condicional (quantidade_disponivel >= quantidade) - não sofre
        lost update sob concorrência, ao contrário de buscar + mutar em memória + atualizar."""
        ...

    async def incrementar_estoque(self, peca_id: int, quantidade: int) -> Peca:
        """UPDATE atômico (quantidade_disponivel + quantidade) - mesma justificativa de
        decrementar_estoque."""
        ...
