from typing import Protocol

from app.domain.servico.entities import Servico


class ServicoRepositoryProtocol(Protocol):
    async def criar(self, servico: Servico) -> Servico: ...
    async def buscar_por_id(self, servico_id: int) -> Servico | None: ...
    async def listar(self) -> list[Servico]: ...
    async def atualizar(self, servico: Servico) -> Servico: ...
    async def remover(self, servico_id: int) -> None: ...
