from typing import Protocol

from app.domain.veiculo.entities import Veiculo


class VeiculoRepositoryProtocol(Protocol):
    async def criar(self, veiculo: Veiculo) -> Veiculo: ...
    async def buscar_por_id(self, veiculo_id: int) -> Veiculo | None: ...
    async def buscar_por_placa(self, placa: str) -> Veiculo | None: ...
    async def existe_com_placa(self, placa: str) -> bool: ...
    async def listar(
        self, cliente_id: int | None = None, limit: int = 50, offset: int = 0
    ) -> list[Veiculo]: ...
    async def atualizar(self, veiculo: Veiculo) -> Veiculo: ...
    async def remover(self, veiculo_id: int) -> None: ...
