"""cria tabela pecas

Revision ID: 451b4aa10607
Revises: 7c8586cf44a9
Create Date: 2026-08-06 14:51:40.169428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451b4aa10607'
down_revision: Union[str, Sequence[str], None] = '7c8586cf44a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantidade_disponivel >= 0', name='ck_pecas_quantidade_nao_negativa'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pecas')
    # ### end Alembic commands ###
