"""cria tabelas ordens_servico, itens_servico e itens_peca

Revision ID: 591afe03e128
Revises: 451b4aa10607
Create Date: 2026-08-06 15:32:11.888064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591afe03e128'
down_revision: Union[str, Sequence[str], None] = '451b4aa10607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RECEBIDA', 'EM_DIAGNOSTICO', 'AGUARDANDO_APROVACAO', 'EM_EXECUCAO', 'FINALIZADA', 'ENTREGUE', 'REPROVADA', 'CANCELADA', name='status_os'), nullable=False),
    sa.Column('recebida_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execucao_iniciada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordens_servico_cliente_id'), 'ordens_servico', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_veiculo_id'), 'ordens_servico', ['veiculo_id'], unique=False)
    op.create_table('itens_peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_peca_ordem_servico_id'), 'itens_peca', ['ordem_servico_id'], unique=False)
    op.create_table('itens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_servico_ordem_servico_id'), 'itens_servico', ['ordem_servico_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_servico_ordem_servico_id'), table_name='itens_servico')
    op.drop_table('itens_servico')
    op.drop_index(op.f('ix_itens_peca_ordem_servico_id'), table_name='itens_peca')
    op.drop_table('itens_peca')
    op.drop_index(op.f('ix_ordens_servico_veiculo_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_cliente_id'), table_name='ordens_servico')
    op.drop_table('ordens_servico')
    # ### end Alembic commands ###
