from typing import Protocol

from app.domain.usuario.entities import Usuario


class UsuarioRepositoryProtocol(Protocol):
    async def buscar_por_email(self, email: str) -> Usuario | None: ...
    async def buscar_por_id(self, usuario_id: int) -> Usuario | None: ...
    async def existe_com_email(self, email: str) -> bool: ...
    async def criar(self, usuario: Usuario) -> Usuario: ...
