from typing import Protocol

from app.domain.cliente.entities import Cliente


class ClienteRepositoryProtocol(Protocol):
    async def criar(self, cliente: Cliente) -> Cliente: ...
    async def buscar_por_id(self, cliente_id: int) -> Cliente | None: ...
    async def buscar_por_documento(self, documento: str) -> Cliente | None: ...
    async def existe_com_documento(self, documento: str) -> bool: ...
    async def listar(self, limit: int = 50, offset: int = 0) -> list[Cliente]: ...
    async def atualizar(self, cliente: Cliente) -> Cliente: ...
    async def remover(self, cliente_id: int) -> None: ...
