from typing import Protocol

from app.domain.ordem_servico.entities import OrdemServico


class OrdemServicoRepositoryProtocol(Protocol):
    async def criar(self, ordem: OrdemServico) -> OrdemServico: ...

    async def buscar_por_id(self, ordem_id: int) -> OrdemServico | None: ...

    async def listar(self) -> list[OrdemServico]: ...

    async def atualizar(self, ordem: OrdemServico) -> OrdemServico: ...
